spring.application.name=zEngine

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/TU_NOMBRE_DE_BASE_DE_DATOS
spring.datasource.username="Nombre_usuario_de_PostgreSQL"
spring.datasource.password="Contraseña_de_PostgreSQL"
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
